// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSIONS: KVNamespace;
	VITRIUM_API_URL: "https://api.vitrium.com";
	AUTH_IDP_BASE_URL: "https://auth.ies.org";
	ALLOW_MEMBERS_WITHOUT_INVITE: "true";
	ENVIRONMENT: string;
	SESSION_ENCRYPTION_KEY: string;
	COOKIE_SIGNING_SECRET: string;
	PDFS: R2Bucket;
	DB: D1Database;
	SEARCH_RATE_LIMITER: RateLimit;
	SEND_EMAIL: SendEmail;
	VECTORIZE: VectorizeIndex;
	VECTORIZE_DEPRECATED: VectorizeIndex;
	AI: Ai;
}
