// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSIONS: KVNamespace;
	VITRIUM_API_URL: "https://api.vitrium.com";
	ENVIRONMENT: "production";
	PDFS: R2Bucket;
	DB: D1Database;
	SEARCH_RATE_LIMITER: RateLimit;
	VECTORIZE: VectorizeIndex;
	VECTORIZE_DEPRECATED: VectorizeIndex;
	AI: Ai;
}
