/**
 * Lensy shared type contracts.
 *
 * Type-only module (erased at build) imported by BOTH the Worker graph and the
 * Node script graph. It is the single source of truth for:
 *   - D1 row shapes (what `.bind(...).all<T>()` returns)
 *   - Vectorize metadata
 *   - the /api/search wire format (request + response)
 *   - the PDF-parse / ingest shapes shared between scripts and the ingest worker
 *
 * `Env` is intentionally NOT here — it is the ambient global generated by
 * `wrangler types` (worker-configuration.d.ts) plus worker-env.d.ts.
 */

// ─── Vectorize ──────────────────────────────────────────────────────────────

export type ChunkType = 'text' | 'table' | 'general_notes' | 'reference' | 'application';

/** Metadata stored on every Vectorize vector (ingest.js). */
export interface VectorMetadata {
  standard_id: string | null;
  application_code: string | null;
  standard_code: string;
  chunk_type: ChunkType;
  page_number: number | null;
  section: string | null;
  excerpt_text: string;
  indoor_outdoor: string | null;
  tm24_eligible: boolean | null;
  /** Only set on deprecated-index vectors. */
  status?: 'current' | 'deprecated';
}

// ─── D1 rows ──────────────────────────────────────────────────────────────────

export type IndoorOutdoor = 'Indoor' | 'Outdoor' | 'Both';

/**
 * A row of the D1 `applications` table (migrations 0001–0006). Column names are
 * the load-bearing wire contract — do not rename. Text columns are nullable.
 */
export interface ApplicationRow {
  id: number;
  code: string;
  Sub_Category: string | null;
  App: string | null;
  App_s1: string | null; App_s2: string | null; App_s3: string | null;
  App_s4: string | null; App_s5: string | null; App_s6: string | null;
  Standard: string | null;
  Standard_Full: string | null;
  Table_Ref: string | null;
  Row_Ref: string | null;
  Page_Number: number | null;
  Link_Mapping: string | null;
  Area_or_Task: string | null;
  Indoor_Outdoor: IndoorOutdoor | null;
  App_Type: string | null;
  Veiling_Risk: string | null;
  Class_of_Play: string | null;
  Hor_Cat: string | null; Hor_Lux: number | null; Hor_Fc: number | null;
  Hor_Height_m: number | null; Hor_Height_ft: number | null;
  Hor_Avg_Max_Min: string | null; Hor_Uniformity: string | null;
  Hor_CV: number | null; Hor_Ratio_Basis: string | null; Hor_Notes: string | null;
  Ver_Cat: string | null; Ver_Lux: number | null; Ver_Fc: number | null;
  Ver_Height_m: number | null; Ver_Height_ft: number | null;
  Ver_Avg_Max_Min: string | null; Ver_Uniformity: string | null;
  Ver_CV: number | null; Ver_Ratio_Basis: string | null; Ver_Notes: string | null;
  Task_Cat: string | null; Task_Lux: number | null; Task_Fc: number | null;
  Task_Height_m: number | null; Task_Height_ft: number | null;
  Task_Avg_Max_Min: string | null; Task_Uniformity: string | null; Task_Notes: string | null;
  TM24_Eligible: 0 | 1;
  TM24_Notes: string | null;
  Lighting_Zone: string | null;
  Max_Glare_Rating: string | null;
  Max_Uplight: string | null;
  Curfew_Dimming: string | null;
  Spectrum_Guidance: string | null;
  Controls_Required: string | null;
  Footnotes: string | null;
  /** JSON: { levels: Record<hierarchyCol, number[]>, row: number[] } — migration 0006. */
  Footnote_Marks: string | null;
  General_Notes: string | null;
  App_Notes: string | null;
  Vitrium_Doc_ID: string | null;
  Vitrium_Deep_Link: string | null;
  Active: 0 | 1;
  Deprecated_By: string | null;
  created_at: string;
  updated_at: string;
}

/** A row of the D1 `standards` table (migrations 0001–0006). */
export interface StandardRow {
  id: string;
  title: string;
  full_designation: string | null;
  description: string | null;
  author: string | null;
  year: number | null;
  edition: string | null;
  status: 'Active' | 'Deprecated';
  supersedes: string | null;
  superseded_by: string | null;
  r2_key: string | null;
  vitrium_doc_id: string | null;
  vitrium_web_url: string | null;
  pages_json: string | null;
  tables_json: string | null;
  chunk_count: number | null;
  page_count: number | null;
  coverage_json: string | null;
  /** { "<markerNumber>": firstBodyPage } — migration 0009, client DO31.4. */
  reference_markers_json: string | null;
  indexed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProjectRow {
  id: number;
  user_id: number;
  name: string;
  location: string | null;
  client_name: string | null;
  client_company: string | null;
  project_type: string | null;
  designer_name: string | null;
  designer_company: string | null;
  target_codes: string | null;
  status: 'Active' | 'Archived';
  notes: string | null;
  share_token: string | null;
  share_expires_at: string | null;
  created_at: string;
  modified_at: string;
}

export interface ProjectApplicationRow {
  id: number;
  project_id: number;
  application_code: string;
  snapshot_data: string | null;
  quantity: number;
  room_names: string | null;
  custom_notes: string | null;
  overridden: 0 | 1;
  override_hor_lux: number | null;
  override_ver_lux: number | null;
  override_reason: string | null;
  sort_order: number;
  added_at: string;
}

export interface SearchLogRow {
  id: number;
  created_at: string;
  query: string;
  result_count: number | null;
  standards_referenced: string | null;
  no_strong_match: number | null;
  cached: number;
}

// ─── Standards index (search.js fetchStandardsIndex) ──────────────────────────

export interface StandardIndexEntry {
  docId: string | null;
  webUrl: string | null;
  status: string;
  supersededBy: string | null;
  title: string | null;
  fullDesignation: string | null;
  /**
   * In-body reference markers: marker number → first page printing it
   * (client DO31.4). null for standards ingested before migration 0009, or for
   * standards that cite by author-date rather than by number.
   */
  referenceMarkers?: Record<string, number> | null;
  /** Authoring technical committee resolved from the `author` column (DO34). */
  committee?: CommitteeCredit | null;
}
export type StandardsIndex = Map<string, StandardIndexEntry>;

// ─── Formatted search wire format (search.js formatApplication) ───────────────

export interface IlluminancePlane {
  category: string | null;
  lux?: number | null;      // stripped by applyUnits when units='fc'
  fc?: number | null;       // stripped when units='lux'
  heightM?: number | null;
  heightFt?: number | null;
  avgMaxMin: string | null;
  uniformity: string | null;
  cv?: number | null;
  ratioBasis?: string | null;
  notes: string | null;
}

export interface OutdoorGuidance {
  lightingZone: string | null;
  maxGlareRating: string | null;
  maxUplight: string | null;
  curfewDimming: string | null;
  spectrumGuidance: string | null;
  controlsRequired: string | null;
}

/** Where footnote markers attach in the printed table (migration 0006). */
export interface FootnoteMarks {
  /** hierarchy column name (Sub_Category, App, App_s1…App_s6) → footnote numbers */
  levels?: Record<string, number[]>;
  /** markers printed on the data row itself */
  row?: number[];
}

/**
 * The application object in a search result. Application-row results carry the
 * full shape; chunk-only results (excerpt/reference) synthesize the minimal
 * fields with hierarchy nulled and add `standardTitle`.
 */
export interface FormattedApplication {
  code: string;
  category: string | null;
  sub1: string | null; sub2: string | null; sub3: string | null;
  sub4?: string | null; sub5?: string | null; sub6?: string | null;
  fullName: string;
  standard: string | null;
  standardFull: string | null;
  standardTitle?: string | null;
  tableRef: string | null;
  rowRef: string | number | null;
  linkMapping?: string | null;
  areaOrTask: string | null;
  indoorOutdoor: IndoorOutdoor | string | null;
  veilingRisk?: string | null;
  classOfPlay?: string | null;
  subCategory?: string | null;
  horizontal: IlluminancePlane | null;
  vertical: IlluminancePlane | null;
  task: IlluminancePlane | null;
  tm24Eligible: boolean;
  tm24Notes?: string | null;
  outdoor: OutdoorGuidance | null;
  footnotes: string | null;
  footnoteMarks: FootnoteMarks | null;
  generalNotes: string | null;
  appNotes: string | null;
}

export interface Excerpt {
  text: string;
  pageNumber: number | null;
  section: string | null;
  chunkType: string;
  /**
   * Page-targeted Lighting Library URL for THIS excerpt (client DO22: the
   * "From the Standard" drop-down carries an "Open in Library" link per
   * excerpt, not one link for the whole card).
   */
  vitriumLink?: string | null;
}

export interface RelatedApplication {
  code: string;
  fullName: string;
  standard: string | null;
  standardFull: string | null;
  horLux: number | null;
  verLux: number | null;
}

export type ReferenceLink = { url: string; type: 'library' | 'doi' | 'url' } | null;

/**
 * One standard whose References section carries the same cited work as this
 * reference result (client DO26.4). `url` opens that standard's References
 * page in the Lighting Library — the closest indexed location to the cited
 * item; in-body superscript reference markers are not indexed.
 */
/** Authoring technical committee credit on a result card (client DO34). */
export interface CommitteeCredit {
  /** Display-ready, always "IES <Committee Name>". */
  name: string;
  /** The committee's public page, or the root committee list when it has none. */
  url: string;
  /** false when `url` is the root list because the name matched no known committee. */
  exact: boolean;
}

export interface ReferenceMarker {
  standard: string;
  standardFull: string | null;
  count: number;
  pageNumber: number | null;
  /** The number this standard printed the entry under, when recoverable. */
  referenceNumber?: number | null;
  /**
   * What pageNumber/url point at (client DO31.4):
   *   'citation'   — the body page where this standard superscripts the marker
   *   'references' — the bibliography page (fallback when no marker was indexed)
   */
  target?: 'citation' | 'references';
  url: string | null;
}

export type ResultType = 'application' | 'excerpt' | 'reference' | 'definition';

/** One ANSI/IES LS-1 definition on a Definition result card (client DO33). */
export interface DefinitionPayload {
  slug: string;
  term: string;
  /** LS-1 clause number the definition is printed under ('4.1'), when present. */
  clause: string | null;
  /** Sanitized rich text — printed IN FULL, may carry emphasis/math/images. */
  html: string;
  sourceUrl: string | null;
}

export interface SearchResult {
  resultType: ResultType;
  application: FormattedApplication;
  relevanceScore: number;
  excerpt: Excerpt | null;
  /**
   * Up to EXCERPTS_PER_RESULT prose excerpts from the same standard, ranked
   * page-near-first (client DO22). `excerpt` stays the best one for
   * back-compatibility.
   */
  excerpts?: Excerpt[];
  citation: string;
  /**
   * The citation WITHOUT its ", p. N" tail, and the page on its own — the UI
   * links the name to the front cover and the page to the internal reference
   * (client DO18: one hyperlink covering both was confusing).
   */
  citationName?: string;
  citationPage?: number | null;
  vitriumLink: string | null;
  /**
   * Front-of-document Lighting Library URL (no page fragment) — the UI links
   * the full-title citation here so users can open the standard and read it
   * through, instead of jumping to a page inside (client feedback DO1R2).
   */
  standardLink?: string | null;
  relatedApplications: RelatedApplication[];
  referenceLink?: ReferenceLink;
  /** Standards whose References sections carry this same cited work (DO26.4). */
  referenceMarkers?: ReferenceMarker[];
  /** Present only on resultType 'definition' (client DO33). */
  definition?: DefinitionPayload;
  /** Authoring technical committee, credited under the citation (DO34). */
  committee?: CommitteeCredit | null;
  isDeprecated?: boolean;
  supersededBy?: string | null;
  deprecationNotice?: string;
}

/** Which prompt the AI Guide ran (client DO24/DO25/DO26.5). */
export type AIMode = 'guide' | 'comparison' | 'references';

/** Editions involved in a version comparison, for the AI header advisory. */
export interface ComparisonContext {
  current: { id: string; name: string; url: string | null } | null;
  /**
   * The prior edition the analysis is actually against — the most recent
   * deprecated one (client DO27), or the edition the query named explicitly.
   * Exactly one entry in practice; an array for wire compatibility with
   * responses cached before DO27.
   */
  deprecated: Array<{ id: string; name: string; url: string | null }>;
  /**
   * Older deprecated editions present in the result set. Listed and linked by
   * the UI so the reader can open them, but excluded from the AI comparison.
   */
  alsoDeprecated?: Array<{ id: string; name: string; url: string | null }>;
}

export interface AISummary {
  text: string;
  watermark: string | null;
  disclaimer: string;
  /** Which prompt produced the text — drives how the UI frames it. */
  mode?: AIMode;
  /**
   * Version-comparison header advisory (DO25): "…[old] is deprecated and has
   * been replaced by the current [new]", with both editions hyperlinked.
   */
  comparison?: ComparisonContext;
  /**
   * True when the text is the no-model safe fallback produced because every
   * AI model attempt errored. Degraded summaries are never cached, so the
   * next identical search retries the models.
   */
  degraded?: boolean;
}

export type ContentType = 'tables' | 'body' | 'references' | 'definitions' | 'compare';

export interface SearchFilters {
  indoor_outdoor?: IndoorOutdoor;
  standard?: string;
  standard_prefix?: string;
  tm24_eligible?: boolean;
  lighting_zone?: string;
  content_types?: ContentType[];
}

export interface SearchRequestBody {
  query: string;
  includeAISummary?: boolean;
  filters?: SearchFilters;
  limit?: number;
  units?: 'lux' | 'fc' | 'both';
  debug?: boolean;
}

export interface SearchResponse {
  query: string;
  expandedQuery?: string;
  isMultiQuery: boolean;
  subQueries?: string[];
  isVersionComparison: boolean;
  contentTypes: ContentType[];
  noStrongMatch: boolean;
  noStrongMatchMessage: string | null;
  results: SearchResult[];
  aiSummary: AISummary | null;
  /**
   * standard id / full designation → front-of-document Lighting Library URL,
   * for every standard in this result set. The UI hyperlinks the standards the
   * AI Guide names in its prose (client DO24).
   */
  standardLinks?: Record<string, string>;
  timestamp: string;
  cached?: boolean;
  _depDbg?: unknown;
}

// ─── Node-side (PDF parse → ingest) ───────────────────────────────────────────

export interface ParsedLine {
  text: string;
  y: number;
  x: number | null;
  fontSize: number;
  bold: boolean;
}

export interface ParsedPage {
  number: number;
  text: string;
  lines: ParsedLine[];
  width: number;
  height: number;
}

export interface PDFMetadata {
  title: string;
  author: string;
  subject: string;
  keywords: string;
  year: string | null;
}

/** Chunk produced by src/lib/chunker.js. */
export interface IESChunk {
  text: string;
  pageNumber: number | null;
  section: string | null;
  type: ChunkType;
  wordCount: number;
}

/** Chunk as sent to POST /api/ingest (subset of IESChunk). */
export interface IngestChunk {
  text: string;
  pageNumber?: number | null;
  section?: string | null;
  type?: ChunkType;
}

export interface IngestRequestBody {
  standardId: string;
  status?: 'current' | 'deprecated';
  structure?: 'new_table' | 'standard';
  metadata?: Partial<{
    title: string; author: string; subject: string;
    year: string | number; fullDesignation: string; pageCount: number;
  }>;
  chunks?: IngestChunk[];
  tables?: TableData[];
  applications?: Partial<ApplicationRow>[];
  r2Key?: string | null;
}

export interface TableData {
  pageNumber: number;
  header?: string;
  rows?: unknown[];
  footnotes?: string;
  generalNotes?: string;
}

/** D1 row: invited_users (migrations/0007_invited_users.sql). */
export interface InvitedUserRow {
  id: number;
  email: string;
  name: string | null;
  organization: string | null;
  role: string;
  status: string;
  person_uuid: string | null;
  expires_at: string | null;
  invited_by: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  last_login_at: string | null;
  /** When the invitation email last went out; NULL means never (migration 0008). */
  invite_sent_at: string | null;
  /** Reason the last send failed, cleared on success. */
  invite_send_error: string | null;
}
